import { AcumuladoContainer } from "@/containers";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Articulos La Nacion</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AcumuladoContainer />
    </>
  );
}
