import { Test } from '@/components'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          
          <Test/>
          
      </main>
    </>
  )
}


{/* <article class="mod-caja-nota living w-100-mobile">
  <section id="" class="cont-figure">
      <a href="" class="figure">
          <picture id="" class="content-pic picture">
              <img src="https://bucket1.glanacion.com/anexos/fotos/22/3054322h600.jpg" alt="" class="content-img">
          </picture>
      </a>
  </section>
  <div class="mod-caja-nota__descrip lugares">
      <h2 class="com-title-acu"><a href=""><b>La escuela.</b> que tiene de escudo al Che Guevara y donde izan la bandera de Cuba</a></h2>
      <h4 class="com-date">1 de Julio de 2019</h4>
  </div>  
</article> */}